/* AUTOMATICALLY GENERATED CODE DO NOT MODIFY */
/*   To generate run: "serverpod generate"    */

// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: public_member_api_docs
// ignore_for_file: type_literal_in_constant_pattern
// ignore_for_file: use_super_parameters
// ignore_for_file: invalid_use_of_internal_member

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _ida;
import 'package:http/http.dart' as _i85jenna;
import 'package:podship_console_client/src/protocol/integrations/models/aws_start.dart'
    as _ini35y01;
import 'package:podship_console_client/src/protocol/integrations/models/integration_view.dart'
    as _i11dr8ol;
import 'package:podship_console_client/src/protocol/integrations/models/provider.dart'
    as _iyg88eji;
import 'package:podship_console_client/src/protocol/workspace/models/me.dart'
    as _iu40c3h3;
import 'package:serverpod_auth_core_client/serverpod_auth_core_client.dart'
    as _iacc;
import 'package:serverpod_auth_idp_client/serverpod_auth_idp_client.dart'
    as _iaic;
import 'package:serverpod_client/serverpod_client.dart' as _isc;
import 'protocol.dart' as _il2as5qe;

/// Sign in with an emailed code or a one-time link.
/// {@category Endpoint}
class EndpointEmailCode extends _isc.EndpointRef {
  EndpointEmailCode(_isc.EndpointCaller caller) : super(caller);

  @override
  String get name => 'emailCode';

  _ida.Future<void> requestCode(
    String email,
    String locale,
  ) => caller.callServerEndpoint<void>(
    'emailCode',
    'requestCode',
    {
      'email': email,
      'locale': locale,
    },
  );

  _ida.Future<_iacc.AuthSuccess> verifyCode(
    String email,
    String code,
  ) => caller.callServerEndpoint<_iacc.AuthSuccess>(
    'emailCode',
    'verifyCode',
    {
      'email': email,
      'code': code,
    },
  );

  /// Redeems `/sign-in/link/<token>`.
  _ida.Future<_iacc.AuthSuccess> redeemLink(String token) =>
      caller.callServerEndpoint<_iacc.AuthSuccess>(
        'emailCode',
        'redeemLink',
        {'token': token},
      );
}

/// By extending [RefreshJwtTokensEndpoint], the JWT token refresh endpoint
/// is made available on the server and enables automatic token refresh on the client.
/// {@category Endpoint}
class EndpointJwtRefresh extends _iacc.EndpointRefreshJwtTokens {
  EndpointJwtRefresh(_isc.EndpointCaller caller) : super(caller);

  @override
  String get name => 'jwtRefresh';

  /// Creates a new token pair for the given [refreshToken].
  ///
  /// If [refreshToken] is omitted, cookie-mode web clients fall back to the
  /// configured HttpOnly refresh cookie. When neither source is present this
  /// throws [RefreshTokenNotFoundException], the same public "no usable refresh
  /// credential" exception used for unknown refresh tokens.
  ///
  /// Can throw the following exceptions:
  /// -[RefreshTokenMalformedException]: refresh token is malformed and could
  ///   not be parsed. Not expected to happen for tokens issued by the server.
  /// -[RefreshTokenNotFoundException]: refresh token is unknown to the server.
  ///   Either the token was deleted or generated by a different server.
  /// -[RefreshTokenExpiredException]: refresh token has expired. Will happen
  ///   only if it has not been used within configured `refreshTokenLifetime`.
  /// -[RefreshTokenInvalidSecretException]: refresh token is incorrect, meaning
  ///   it does not refer to the current secret refresh token. This indicates
  ///   either a malfunctioning client or a malicious attempt by someone who has
  ///   obtained the refresh token. In this case the underlying refresh token
  ///   will be deleted, and access to it will expire fully when the last access
  ///   token is elapsed.
  ///
  /// This endpoint is unauthenticated, meaning the client won't include any
  /// authentication information with the call.
  @override
  _ida.Future<_iacc.AuthSuccess> refreshAccessToken({String? refreshToken}) =>
      caller.callServerEndpoint<_iacc.AuthSuccess>(
        'jwtRefresh',
        'refreshAccessToken',
        {'refreshToken': refreshToken},
        authenticated: false,
      );
}

/// The integrations page (spec INT). Every call needs a signed-in member;
/// connect and disconnect need an owner or admin (INT-3).
/// {@category Endpoint}
class EndpointIntegrations extends _isc.EndpointRef {
  EndpointIntegrations(_isc.EndpointCaller caller) : super(caller);

  @override
  String get name => 'integrations';

  _ida.Future<List<_i11dr8ol.IntegrationView>> list() =>
      caller.callServerEndpoint<List<_i11dr8ol.IntegrationView>>(
        'integrations',
        'list',
        {},
      );

  /// The Cloudflare dashboard link with the permissions filled in (INT-8).
  _ida.Future<String> cloudflareTokenUrl() => caller.callServerEndpoint<String>(
    'integrations',
    'cloudflareTokenUrl',
    {},
  );

  _ida.Future<_i11dr8ol.IntegrationView> saveCloudflare(String token) =>
      caller.callServerEndpoint<_i11dr8ol.IntegrationView>(
        'integrations',
        'saveCloudflare',
        {'token': token},
      );

  _ida.Future<_ini35y01.AwsStart> startAws() =>
      caller.callServerEndpoint<_ini35y01.AwsStart>(
        'integrations',
        'startAws',
        {},
      );

  _ida.Future<_i11dr8ol.IntegrationView> disconnect(
    _iyg88eji.IntegrationProvider provider,
  ) => caller.callServerEndpoint<_i11dr8ol.IntegrationView>(
    'integrations',
    'disconnect',
    {'provider': provider},
  );

  _ida.Future<_i11dr8ol.IntegrationView> check(
    _iyg88eji.IntegrationProvider provider,
  ) => caller.callServerEndpoint<_i11dr8ol.IntegrationView>(
    'integrations',
    'check',
    {'provider': provider},
  );
}

/// {@category Endpoint}
class EndpointMe extends _isc.EndpointRef {
  EndpointMe(_isc.EndpointCaller caller) : super(caller);

  @override
  String get name => 'me';

  _ida.Future<_iu40c3h3.Me> get() => caller.callServerEndpoint<_iu40c3h3.Me>(
    'me',
    'get',
    {},
  );
}

class Modules {
  Modules(Client client) {
    serverpod_auth_idp = _iaic.Caller(client);
    serverpod_auth_core = _iacc.Caller(client);
  }

  late final _iaic.Caller serverpod_auth_idp;

  late final _iacc.Caller serverpod_auth_core;
}

class Client extends _isc.ServerpodClientShared {
  Client(
    String host, {
    dynamic securityContext,
    Duration? streamingConnectionTimeout,
    Duration? connectionTimeout,
    Function(
      _isc.MethodCallContext,
      Object,
      StackTrace,
    )?
    onFailedCall,
    Function(_isc.MethodCallContext)? onSucceededCall,
    bool? disconnectStreamsOnLostInternetConnection,
    _i85jenna.Client? httpClientOverride,
  }) : super(
         host,
         _il2as5qe.Protocol(),
         securityContext: securityContext,
         streamingConnectionTimeout: streamingConnectionTimeout,
         connectionTimeout: connectionTimeout,
         onFailedCall: onFailedCall,
         onSucceededCall: onSucceededCall,
         disconnectStreamsOnLostInternetConnection:
             disconnectStreamsOnLostInternetConnection,
         httpClientOverride: httpClientOverride,
       ) {
    emailCode = EndpointEmailCode(this);
    jwtRefresh = EndpointJwtRefresh(this);
    integrations = EndpointIntegrations(this);
    me = EndpointMe(this);
    modules = Modules(this);
  }

  late final EndpointEmailCode emailCode;

  late final EndpointJwtRefresh jwtRefresh;

  late final EndpointIntegrations integrations;

  late final EndpointMe me;

  late final Modules modules;

  @override
  Map<String, _isc.EndpointRef> get endpointRefLookup => {
    'emailCode': emailCode,
    'jwtRefresh': jwtRefresh,
    'integrations': integrations,
    'me': me,
  };

  @override
  Map<String, _isc.ModuleEndpointCaller> get moduleLookup => {
    'serverpod_auth_idp': modules.serverpod_auth_idp,
    'serverpod_auth_core': modules.serverpod_auth_core,
  };
}
