// Writes lib/src/remote/assets.g.dart from lib/src/remote/assets/*.sh.
//
//   dart run tool/embed_assets.dart
//
// The scripts are embedded so `dart pub global activate` installs a
// self-contained tool. A test fails when the generated file is stale.
import 'dart:io';

void main() {
  stdout.write(render());
  File('lib/src/remote/assets.g.dart').writeAsStringSync(render());
}

String render() {
  final dir = Directory('lib/src/remote/assets');
  final files = dir.listSync().whereType<File>().toList()
    ..sort((a, b) => a.path.compareTo(b.path));
  final b = StringBuffer()
    ..writeln('// GENERATED by tool/embed_assets.dart. Do not edit.')
    ..writeln('// Edit lib/src/remote/assets/*.sh and run the tool again.')
    ..writeln()
    ..writeln('/// The server scripts, by file name.')
    ..writeln('const remoteAssets = <String, String>{');
  for (final f in files) {
    final name = f.uri.pathSegments.last;
    final text = f.readAsStringSync();
    if (text.contains("'''")) throw StateError("$name contains '''");
    b.writeln("  '$name': r'''$text''',");
  }
  b.writeln('};');
  return b.toString();
}
